#!/usr/bin/env ruby
require_relative "../lib/firew0rks.rb"
require 'reline'

terminal = Reline::ANSI.new
terminal.hide_cursor

trap("INT") {
  terminal.show_cursor
  puts ""
  puts "Bye."
  exit 0
}


begin
  Fireworks.new.run
rescue => error
  puts error
ensure
  terminal.show_cursor
end
